Desktop/ROR/secr/config/routes.rb
Secr::Application.routes.draw do
  resources :secryties

  resources :secries

end

Desktop/ROR/secr/app/models/secry.rb
class Secry < ActiveRecord::Base
  attr_accessible :name, :tuoi
end

Desktop/ROR/secr/app/models/secryty.rb
class Secryty < ActiveRecord::Base
  attr_accessible :cmt, :name
end

Desktop/ROR/secr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Desktop/ROR/secr/app/controllers/secries_controller.rb
class SecriesController < ApplicationController
  # GET /secries
  # GET /secries.json
  def index
    @secries = Secry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @secries }
    end
  end

  # GET /secries/1
  # GET /secries/1.json
  def show
    @secry = Secry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @secry }
    end
  end

  # GET /secries/new
  # GET /secries/new.json
  def new
    @secry = Secry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @secry }
    end
  end

  # GET /secries/1/edit
  def edit
    @secry = Secry.find(params[:id])
  end

  # POST /secries
  # POST /secries.json
  def create
    @secry = Secry.new(params[:secry])

    respond_to do |format|
      if @secry.save
        format.html { redirect_to @secry, notice: 'Secry was successfully created.' }
        format.json { render json: @secry, status: :created, location: @secry }
      else
        format.html { render action: "new" }
        format.json { render json: @secry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /secries/1
  # PUT /secries/1.json
  def update
    @secry = Secry.find(params[:id])

    respond_to do |format|
      if @secry.update_attributes(params[:secry])
        format.html { redirect_to @secry, notice: 'Secry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @secry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secries/1
  # DELETE /secries/1.json
  def destroy
    @secry = Secry.find(params[:id])
    @secry.destroy

    respond_to do |format|
      format.html { redirect_to secries_url }
      format.json { head :no_content }
    end
  end
end

Desktop/ROR/secr/app/controllers/secryties_controller.rb
class SecrytiesController < ApplicationController
  # GET /secryties
  # GET /secryties.json
  def index
    @secryties = Secryty.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @secryties }
    end
  end

  # GET /secryties/1
  # GET /secryties/1.json
  def show
    @secryty = Secryty.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @secryty }
    end
  end

  # GET /secryties/new
  # GET /secryties/new.json
  def new
    @secryty = Secryty.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @secryty }
    end
  end

  # GET /secryties/1/edit
  def edit
    @secryty = Secryty.find(params[:id])
  end

  # POST /secryties
  # POST /secryties.json
  def create
    @secryty = Secryty.new(params[:secryty])

    respond_to do |format|
      if @secryty.save
        format.html { redirect_to @secryty, notice: 'Secryty was successfully created.' }
        format.json { render json: @secryty, status: :created, location: @secryty }
      else
        format.html { render action: "new" }
        format.json { render json: @secryty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /secryties/1
  # PUT /secryties/1.json
  def update
    @secryty = Secryty.find(params[:id])

    respond_to do |format|
      if @secryty.update_attributes(params[:secryty])
        format.html { redirect_to @secryty, notice: 'Secryty was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @secryty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secryties/1
  # DELETE /secryties/1.json
  def destroy
    @secryty = Secryty.find(params[:id])
    @secryty.destroy

    respond_to do |format|
      format.html { redirect_to secryties_url }
      format.json { head :no_content }
    end
  end
end

Desktop/ROR/secr/app/helpers/application_helper.rb
module ApplicationHelper
end

Desktop/ROR/secr/app/helpers/secries_helper.rb
module SecriesHelper
end

Desktop/ROR/secr/app/helpers/secryties_helper.rb
module SecrytiesHelper
end

Desktop/ROR/secr/app/views/secryties/_form.html.erb
<%= form_for(@secryty) do |f| %>
  <% if @secryty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@secryty.errors.count, "error") %> prohibited this secryty from being saved:</h2>

      <ul>
      <% @secryty.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cmt %><br />
    <%= f.text_field :cmt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Desktop/ROR/secr/app/views/secryties/edit.html.erb
<h1>Editing secryty</h1>

<%= render 'form' %>

<%= link_to 'Show', @secryty %> |
<%= link_to 'Back', secryties_path %>

Desktop/ROR/secr/app/views/secryties/index.html.erb
<h1>Listing secryties</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Cmt</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @secryties.each do |secryty| %>
  <tr>
    <td><%= secryty.name %></td>
    <td><%= secryty.cmt %></td>
    <td><%= link_to 'Show', secryty %></td>
    <td><%= link_to 'Edit', edit_secryty_path(secryty) %></td>
    <td><%= link_to 'Destroy', secryty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Secryty', new_secryty_path %>

Desktop/ROR/secr/app/views/secryties/new.html.erb
<h1>New secryty</h1>

<%= render 'form' %>

<%= link_to 'Back', secryties_path %>

Desktop/ROR/secr/app/views/secryties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @secryty.name %>
</p>

<p>
  <b>Cmt:</b>
  <%= @secryty.cmt %>
</p>


<%= link_to 'Edit', edit_secryty_path(@secryty) %> |
<%= link_to 'Back', secryties_path %>